# Generated by Django 6.0.1 on 2026-01-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Цена за час', max_digits=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
