# Generated by Django 6.0.1 on 2026-01-30 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TutorStudent',
            new_name='TutorStudentRelation',
        ),
        migrations.AlterModelOptions(
            name='tutorstudentrelation',
            options={},
        ),
        migrations.AlterField(
            model_name='tutorstudentrelation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='accounts.studentprofile'),
        ),
        migrations.AlterField(
            model_name='tutorstudentrelation',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.tutorprofile'),
        ),
        migrations.AlterModelTable(
            name='tutorstudentrelation',
            table='tutor_student_relations',
        ),
    ]
