# Generated by Django 6.0.1 on 2026-02-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0002_rename_tutorstudent_tutorstudentrelation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorstudentrelation',
            name='target',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tutorstudentrelation',
            name='type_class',
            field=models.CharField(blank=True, choices=[('Online', 'Онлайн'), ('Ofline', 'Офлайн'), ('Mixed', 'Смешанные')], max_length=10),
        ),
    ]
