# Generated by Django 6.0.1 on 2026-02-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0003_tutorstudentrelation_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorstudentrelation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
