# Generated by Django 6.0.1 on 2026-02-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0004_tutorstudentrelation_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorstudentrelation',
            name='type_class',
            field=models.CharField(blank=True, choices=[('Online', 'Онлайн'), ('Offline', 'Офлайн'), ('Mixed', 'Смешанные')], max_length=10),
        ),
    ]
