# Generated by Django 6.0.1 on 2026-02-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0005_alter_tutorstudentrelation_type_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorstudentrelation',
            name='type_class',
            field=models.CharField(blank=True, choices=[('online', 'Онлайн'), ('offline', 'Офлайн'), ('mixed', 'Смешанные')], max_length=10),
        ),
    ]
