# Generated by Django 6.0.1 on 2026-02-03 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0006_alter_tutorstudentrelation_type_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorstudentrelation',
            old_name='type_class',
            new_name='lesson_type',
        ),
    ]
