# Generated by Django 6.0.1 on 2026-02-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('month', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='image',
            field=models.ImageField(default='months/default.jpg', upload_to='months/'),
        ),
    ]
